server:
  port: 9091
  servlet:
    context-path: /
spring:
  application:
    name: feng-api
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    bootstrap-servers: 10.134.1.24:9092,10.134.1.25:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 手动提交
      group-id: hy-otc
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 60000
    listener:
      log-container-config: false
      concurrency: 5
      # 手动提交
      ack-mode: manual
  redis:
    database: 0
    password: 123456
    sentinel:
      master: mymaster
      nodes:
        - 10.134.1.27:26379
        - 10.134.1.27:26479
        - 10.134.1.27:26579
    lettuce:
      pool:
        max-active: 1000
        max-idle: 50
        min-idle: 20
        max-wait: -1
dubbo:
  registry:
    address: zookeeper://10.134.1.25:3002
  protocol:
    name: dubbo
    port: 20899
springfox:
  documentation:
    # 总开关（同时设置auto-startup=false，否则/v3/api-docs等接口仍能继续访问）
    enabled: true
    auto-startup: true
    swagger-ui:
      enabled: true
